config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :users do
    resources :projects
  end
  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha => true

  def headers
    {
    :subject => "Contact Form",
    :to => "legarrecarnaud.92@gmail.com",
    :from => %("#{name}" <#{email}>)
    }
  end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, uniqueness: true
  validates :project_type, presence: true
  validates :description, length: { maximum: 140 }
  # validates :used_techno, presence: true
  validates :link, presence: true, uniqueness: true

  has_one_attached :image

  COLLECTION = ["E-commerce", "Showcase", "Marketplace", "Social network"]
  TYPE = ["RoR", "JavaScript","HTML5","SCSS"]

  def project_image
    if image.attached?
      image.key
    else
      "504708-200_yey0vr"
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, length: { maximum: 140 }
  # validates :facebook, uniqueness: true
  # validates :instagram, uniqueness: true
  # validates :twitter, uniqueness: true
  # validates :linkedin, uniqueness: true
  # validates :phone_number, uniqueness: true
  validates :job_title, length: { maximum: 40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description, :facebook, :instagram, :twitter, :linkedin, :phone_number, :job_title])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :description, :facebook, :instagram, :twitter, :linkedin, :phone_number, :job_title])
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :projects ]

  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show, :userprojects ]

  def index
    @user_selected = params[:user_id].to_i

    @projects = Project.where(user: @user_selected)
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user=current_user
    @project_type_values = projecttype(params["project"]["project_type"])
    @project.project_type = @project_type_values
    @used_techno_values = usedtechno(params["project"]["used_techno"])
    @project.used_techno = @used_techno_values
    @project.save!
    redirect_to user_projects_path(current_user)
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(params[:project])
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to user_projects_path
  end

    private

  def projecttype(project_type_values)
    resultat = project_type_values.join(",")
    resultat[1..-1]
  end

  def usedtechno(used_techno_values)
    resultat = used_techno_values.join(",")
    resultat[1..-1]
  end

    def project_params
      params.require(:project).permit(:name, :project_type, :description, :date_of_publication, :used_techno, :link, :user_id, :image )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to root_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :description, :facebook, :instagram, :twitter, :linkedin, :phone_number, :country, :birth_date, :job_title, :id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.html.erb
<div class="wrapper">
<div class = "confirmationcontent">
  <h1>✅</h1>
  <p>I'll get back to you soon.</p>
</div>
<%= link_to root_path do%>
  <i class="fa-solid fa-left">back</i>
<% end %>

</div>

app/views/contacts/new.html.erb
<div class="wrapper">
  <div class="formtitle">
    <h1>CONTACT</h1>
  </div>
  <%= simple_form_for @contact do |f| %>
    <div class="form-inputs">
      <%= f.label :name %><br>
      <%= f.text_field :name, required: true %>
      <br>
       <%= f.label :email %><br>
       <%= f.email_field :email, required: true %>
      <br>
       <%= f.label :message %><br>
      <%# <div class="textmailfield"> %>
        <%= f.text_area :message, rows: 8, cols: 47, required: true,
            placeholder: "Send me a message"%></br>
      <%# </div> %>
      <div class="hidden">
        <%= f.label :nickname %><br>
        <%= f.text_field :nickname, hint: 'leave this field blank' %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Send Mail", class:"submitButton" %>
     </div>
  <% end %>
  <div class="icones space-evenly">
      <div class="icon twitter">
        <div class="tooltip">linkedin</div>
        <%= link_to "https://www.linkedin.com/in/arnaud-le-garrec-3260a317b/", :target => "_blank" do%>
          <span><i class="fab fa-linkedin"></i></span>
        <% end %>
      </div>
      <div class="icon github">
        <div class="tooltip">github</div>
        <%= link_to "https://github.com/Arndau", :target => "_blank" do%>
          <span><i class="fab fa-github"></i></span>
        <% end %>
      </div>
  </div>
<%# </div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="backbtn">
      <% unless controller_name == 'users' && action_name == 'index' %>
        <%= link_to root_path, class:"navbar-back" do %>
          <i class="fa-solid fa-circle-left"> BACK</i>
        <% end %>
      <% end %>
    </div>

      <%= render 'shared/dropdown' %>
      <%= render 'shared/flashes' %>

      <%= yield %>
  </body>

</html>

app/views/pages/home.html.erb
 <div class="card-1">
        <%=link_to project.link, :target => "_blank" do %>
          <%= cl_image_tag project.project_image, style:" width: 100%; height: 100%; object-fit: cover;  opacity: 0.5; border-radius: 10px; filter: blur(1px) "%>
          <div class="card-content-centered">
            <h1><%=project.name%><%=project.user_id %></h1>
            <%# <h3> blabla </h3> %>
            <p class="project-description"><%=project.description%></p>
          </div>
          <div class="bubles">
          <div class = "type">
            <% @skills = project.project_type.split(",") %>
            <% @skills.each do |skill|%>
              <p class="project-type">#<%=skill%></p>
            <% end %>
          </div>
          <div class = "techno">
            <% @technos = project.used_techno.split(",")%>
            <% @technos.each do |techno|%>
              <p class="project-used_techno">#<%=techno%></p>
            <% end %>
          </div>
          </div>
        <% end %>
        </div>

app/views/projects/index.html.erb
 <div class="projects-container">
  <div class="row d-flex justify-content-around">
    <% @projects.each do |project| %>
      <div class="col-lg-3 col-md-4 col-sm-6">

     <div class="card-1">
        <%=link_to project.link, :target => "_blank" do %>
          <%= cl_image_tag project.project_image, style:"width: 95%; height: 75%; object-fit: cover;  opacity: 0.5; border-radius: 10px; filter: blur(1px); margin-left: 2.25%; margin-top: 15%"%>
          <div class="card-content-centered">
            <h1><%=project.name%></h1>
            <%# <h3> blabla </h3> %>
            <p class="project-description"><%=project.description%></p>
          </div>
          <div class="bubles">
            <div class = "type">
              <% @skills = project.project_type.split(",") %>
              <% @skills.each do |skill|%>
                <p class="project-type">#<%=skill%></p>
              <% end %>
            </div>
            <div class = "techno">
              <% @technos = project.used_techno.split(",")%>
              <% @technos.each do |techno|%>
                <p class="project-used_techno">#<%=techno%></p>
              <% end %>
            </div>
          </div>
        <% end %>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="wrapper">
  <h1 class="header">报名</h1>
  <p class="headerText">Create a new project</p>

<%= simple_form_for ([:user, @project]) do |f| %>
  <div class="form-inputs">
    <%= f.input :name, label: "What's the name of this project ?"%>
    <%#= f.input :project_type, label: "What's the type of this project ?"%>
    <%= f.input :project_type, as: :check_boxes, collection: Project::COLLECTION %>
    <%= f.input :description, placeholder: "Max 140 characteres"%>
    <%= f.input :date_of_publication %>
    <%= f.input :used_techno, collection: ['RoR', 'HTML5', 'CSS', 'SCSS', 'JavaScript'], :multiple => true, :as => :check_boxes, required: false, include_blank: false %>
    <%= f.input :link, placeholder: "Copy/Past a link of your work in this field"%>
    <%= f.input :image, as: :file %>
  </div>

   <div class="form-actions">
      <%= f.button :submit, "NEW PROJECT", class:"submitButton" %>
     </div>
   <% end %>

</div>

app/views/projects/userprojects.html.erb
 <div class="projects-container">
  <div class="row d-flex justify-content-around">
    <%= @projects.each do |project| %>
      <div class="col-lg-4 col-sm-6">
        <div class="card-1">
          <%= cl_image_tag project.project_image, style:" width: 100%; height: 100%; object-fit: cover;  opacity: 0.5; border-radius: 10px; filter: blur(1px) "%>
          <div class="card-content-centered">
            <h1><%=project.name%></h1>
            <h3><%=link_to "SEE WEBSITE", "https://www.poner.io/", :target => "_blank" %></h3>
            <p class="project-description"><%=project.description%></p>
          </div>
          <div class="bubles">
            <p class="project-type"><%= "project type"%></p>
            <p class="project-used_techno"><%="used_techno"%></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_dropdown.html.erb
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
    MENU
  </button>
  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
    <% if user_signed_in? %>
      <li><%=link_to "Edit profile",  edit_user_registration_path(current_user.id), class:"dropdown-item "  %></li>
      <li><%=link_to "Add a project", new_user_project_path(:user_id), class:"dropdown-item"  %></li>
      <li><hr class="dropdown-divider"></li>
      <li><%=link_to "Logout", destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
    <% else %>
      <li><%=link_to "Connexion", new_user_session_path, class:"dropdown-item" %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/users/index.html.erb
<div class = "card-container"></div>
  <div class="row d-flex justify-content-around">
    <% @users.each do |user| %>
      <div class="col-lg-12 col-md-12 col-sm-6">
        <div class="card" data-state="#about">
          <div class="card-header">
          <div class="card-cover" style="background-image: url('https://images.unsplash.com/photo-1549068106-b024baf5062d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80')"></div>
          <img class="card-avatar" src="https://media-exp1.licdn.com/dms/image/C4E03AQFpVzxPZc8eqg/profile-displayphoto-shrink_400_400/0/1650365741225?e=1655942400&v=beta&t=VWXGY9VUBepbqBxF0t3eT062ZZUSbwRITwB7YdG9Ia8" alt="avatar" />
            <%#= cl_image_tag @user.profile_picture%>
          <h1 class="card-fullname">Arnaud Le Garrec<%=user.id%></h1>
          <h2 class="card-jobtitle">Ruby on Rails Developer</h2>
          </div>
          <div class="card-main">
          <div class="card-section is-active" id="about">
            <div class="card-content">
              <div class="card-subtitle">ABOUT</div>
              <p class="card-desc"> I am a freelance web developer working with <strong>ruby on rails</strong> for the back-end side. I enjoy using <strong>Shopify</strong> for the e-commerce projects.
              To see some of my projects or contact me click the links bellow.
              </p>
            </div>
          </div>
          <div class="card-buttons">
              <%=link_to   user_projects_path(user) do %>
              <button data-section="#experience">PROJECTS</button>
              <% end %>
              <%=link_to new_contact_path(user.id) do %>
              <button data-section="#contact">CONTACT</button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= link_to "CONTACT",new_contact_path%>

<div class="contact">
  <h1>CONTACT</h1>

  <div class="icones space-evenly">
      <div class="icon twitter">
        <div class="tooltip">linkedin</div>
        <%= link_to "https://www.linkedin.com/in/arnaud-le-garrec-3260a317b/", :target => "_blank" do%>
          <span><i class="fab fa-linkedin"></i></span>
        <% end %>
      </div>
  <div class="icon github">
        <div class="tooltip">github</div>
        <%= link_to "https://github.com/Arndau", :target => "_blank" do%>
          <span><i class="fab fa-github"></i></span>
        <% end %>
      </div>
</div>